### PR TITLE
`INT-123` - eat/int 123 remove axios

### PR DESCRIPTION
**Pull request by thiagosaife**
## Pull request type

Removal of axios' dependency.

Jira Link: [INT-123](https://storyblok.atlassian.net/browse/INT-123)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other (please describe):

## How to test this PR

This PR adds updated information to the README file, related to axios' removal.
You don't need to install axios anymore. So, you might try a brand new installation, like described on the updated README file.
You should make tests by reproducing the same behavior of the SDK with axios. Instantiate the `StoryblokClient` on a dummy application, as described on our documentation and try to make all the API requests. You should also install a `responseInterceptor` and try to remove it with the new function `ejectInterceptor`. 

## What is the new behavior?

- A new function to eject the responseInterceptor was added: `ejectInterceptor`
- The Proxy option was removed.

## Other information

Any questions, feel free to ask me.

### CODE REVIEW

**Review by fernandacanto — APPROVED** [review]
Good job my friend! 👏🏻  💪🏻

**Review by joaokamun — APPROVED** [review]
LGTM. Nice work :)

**Comment by thiagosaife** [comment]
@joaokamun , @fernandacanto , @carlosricciardi-storyblok and @christianzoppi . When you have the time, please take a look again in this case. Now the SDK can run under Node's or Web's environments. If you have any question, just let me know. Have a nice weekend, guys!

**Review by fernandacanto — CHANGES_REQUESTED** [review]
Hi @thiagosaife, I created a default node project, using express and tried to use the project in your branch, but unfortunately I am getting the following error: 
`error ReferenceError: AbortController is not defined`

**Comment by thiagosaife** [comment]
@fernandacanto and @christianzoppi Thanks for the feedback. I updated this PR with `isomorphic-fetch` library. I guess now by running `npm t` both of you won't have any issues. Thank you guys!

**Review by fernandacanto — APPROVED** [review]
Great work, my friend!

**Comment by thiagosaife** [comment]
Hello @gijsroge.

Thanks for your attention on this matter. Yes, unfortunately we had to replace for `isomorfic-fetch` because of users that would use our SDK under node's environment. Fetch is working just for browsers in old node's versions. That's why we decided to use `isomorfic-fetch`. But for browser's users, `isomorfic-fetch` checks whether environment the application is running under, and do the proper adjustments to not oversize the final bundle, and the lib itself is much more lightweight than `axios`. In the future, we will get rid of `isomorfic-fetch` and let just the native `fetch` api. But for now, we have to think that we have this annoying limitation.

**Comment by gijsroge** [comment]
@thiagosaife yeah I didn't really think about the fact that if you use this inside for example Next, and you wouldn't provide the isomorphic fetch it's probably not going to work indeed.

Fetch has been introduced in node 17.5, the current version is 18.1. You could argue that maybe you can introduce a breaking version that only supports >=17.5 by default but do provide a compatibility build that has `isomorphic-fetch`?

**Review by fernandacanto — APPROVED** [review]
For me this works, good job!

**Comment by dohomi** [comment]
this would be terrific!

**Pull request merged**
